name = "read-chinese-menu-api"
main = "worker.js"
compatibility_date = "2026-01-27"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "CARDS_KV"
id = "17c3f17f0ede460e9dce6186ed6eaf3f"

[[kv_namespaces]]
binding = "USER_USAGE"
id = "5bf7f707e17747719b812d3d7d0b038e"

[vars]
ENVIRONMENT = "production"
ENABLE_DEV_MODE = "true"  # <--- 添加这一行，确保点数校验被跳过