name: Build and Deploy Blog

on:
  push:
    branches:
      - main
    paths:
      - 'src/data/posts.json'
      - '.github/workflows/deploy.yml'
  # 添加下面这两行，你就能看到 Run workflow 按钮了
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4 # 修正了之前的 actions/checkout 错误
        with:
          node-version: 18
          cache: 'npm'

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages